project_id = "wrriittiqsmzbapbrcwm"

[functions.gerar-discurso]
verify_jwt = false

[functions.analisar-noticia]
verify_jwt = false

[functions.extrair-noticias]
verify_jwt = false

[functions.gerar-projeto-lei]
verify_jwt = false

[functions.consultar-dados-eleitorais]
verify_jwt = false

[functions.gerar-midia]
verify_jwt = false